name: Update Ranking

on:
  schedule:
    - cron: "0 5 * * *"  # 毎日0時 (JSTでは9時)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install requests
      - run: python fetch.py

      - run: git config user.name "github-actions"
      - run: git config user.email "actions@github.com"
      - run: git add ranking.json
      - run: git commit -m "Auto update" || echo "No changes"
      - run: git push
